package backend;

public class InstructionSetThumb {
	public enum ADD {
        ADD,ADDS
      }
	public enum NEG{
		NEG,NEGS
	}
	public enum LSL{
		LSL
	}
	public enum LSR{
		LSR
	}
	public enum ASR{
		ASR
	}
	public enum ROR{
		ROR
	}
	public enum MUL {
        MUL,MULS
      }

	public enum EOR {
        EOR,EORS
      }

	public enum ADC {ADC,ADCS}

	public enum AND{
		AND,ANDS
	}

	public enum CMN{CMN,CMNEQ,CMNNE,CMNHS,CMNLO,CMNMI,
        CMNPL,CMNVS,CMNVC,CMNHI,CMNLS,CMNGE,CMNLT,CMNGT,
        CMNLE,CMNAL}


	public enum MRS{MRS,MRSEQ,MRSNE,MRSHS,MRSLO,MRSMI,
        MRSPL,MRSVS,MRSVC,MRSHI,MRSLS,MRSGE,MRSLT,MRSGT,
        MRSLE,MRSAL}

	public enum MSR{MSR,MSREQ,MSRNE,MSRHS,MSRLO,MSRMI,
        MSRPL,MSRVS,MSRVC,MSRHI,MSRLS,MSRGE,MSRLT,MSRGT,
        MSRLE,MSRAL}
	public enum CMP{CMP,CMPEQ,CMPNE,CMPHS,CMPLO,CMPMI,
        CMPPL,CMPVS,CMPVC,CMPHI,CMPLS,CMPGE,CMPLT,CMPGT,
        CMPLE,CMPAL}

	public enum XOR{EOR,EORS}
	
	public enum SUB{SUB,SUBS}
	public enum SBC{SBC,SBCS}
	
	public enum RSB{RSB,RSBS}
	
	public enum RSC{RSC,RSCS}
	
	public enum TST{TST,TSTEQ,TSTNE,TSTHS,TSTLO,TSTMI,
        TSTPL,TSTVS,TSTVC,TSTHI,TSTLS,TSTGE,TSTLT,TSTGT,
        TSTLE,TSTAL}
	
	public enum TEQ{TEQ,TEQEQ,TEQNE,TEQHS,TEQLO,TEQMI,
        TEQPL,TEQVS,TEQVC,TEQHI,TEQLS,TEQGE,TEQLT,TEQGT,
        TEQLE,TEQAL}
	
	public enum ORR{ORR,ORRS}
	public enum MOV{MOV,MOVS}
	public enum MVN{MVN,MVNS}
	
	public enum B{B,BEQ,BNE,BCS,BCC,BMI,
        BPL,BVS,BVC,BHI,BLS,BGE,BLT,BGT,
        BLE,BAL}
	
	public enum BL{BL,BLEQ,BLNE,BLHS,BLLO,BLMI,
        BLPL,BLVS,BLVC,BLHI,BLLS,BLGE,BLLT,BLGT,
        BLLE,BLAL}

	public enum BIC{BIC,BICS}
	public enum BKPT{BKPT}
	
	public enum BLX{BLX,BLXEQ,BLXNE,BLXHS,BLXLO,BLXMI,
        BLXPL,BLXVS,BLXVC,BLXHI,BLXLS,BLXGE,BLXLT,BLXGT,
        BLXLE,BLXAL}
	
	public enum BX{BX,BXEQ,BXNE,BXHS,BXLO,BXMI,
        BXPL,BXVS,BXVC,BXHI,BXLS,BXGE,BXLT,BXGT,
        BXLE,BXAL}
	
	public enum CPD{CPD,CPDEQ,CPDNE,CPDHS,CPDLO,CPDMI,
        CPDPL,CPDVS,CPDVC,CPDHI,CPDLS,CPDGE,CPDLT,CPDGT,
        CPDLE,CPDAL,CPD2}
	
	public enum LDR{LDR}
	
	public enum LDM{LDMFD,LDMHIED,LDMLSED,LDMGEED,LDMLTED,LDMGTED,
        LDMLEED,LDMALED}
	
	public enum STM{STMFD,STMALED}
	
	public enum LDRB{LDRB,LDREQB,LDRNEB,LDRHSB,LDRLOB,LDRMIB,
        LDRPLB,LDRVSB,LDRVCB,LDRHIB,LDRLSB,LDRGEB,LDRLTB,LDRGTB,
        LDRLEB,LDRALB}
	public enum LDRBT{LDRBT,LDREQBT,LDRNEBT,LDRHSBT,LDRLOBT,LDRMIBT,
        LDRPLBT,LDRVSBT,LDRVCBT,LDRHIBT,LDRLSBT,LDRGEBT,LDRLTBT,LDRGTBT,
        LDRLEBT,LDRALBT}
	public enum LDRH{
		LDRH,LDREQH,LDRNEH,LDRHSH,LDRLOH,LDRMIH,
		LDRPLH,LDRVSH,LDRVCH,LDRHIH,LDRLSH,LDRGEH,LDRLTH,LDRGTH,
		LDRLEH,LDRALH
	}

	public enum LDRSB{
		LDRSB,LDREQSB,LDRNESB,LDRHSSB,LDRLOSB,LDRMISB,
		LDRPLSB,LDRVSSB,LDRVCSB,LDRHISB,LDRLSSB,LDRGESB,LDRLTSB,LDRGTSB,
		LDRLESB,LDRALSB
	}

public enum LDRSH{
LDRSH,LDREQSH,LDRNESH,LDRHSSH,LDRLOSH,LDRMISH,
LDRPLSH,LDRVSSH,LDRVCSH,LDRHISH,LDRLSSH,LDRGESH,LDRLTSH,LDRGTSH,
LDRLESH,LDRALSH
}

public enum LDRT{
LDRT,LDREQT,LDRNET,LDRHST,LDRLOT,LDRMIT,
LDRPLT,LDRVST,LDRVCT,LDRHIT,LDRLST,LDRGET,LDRLTT,LDRGTT,
LDRLET,LDRALT
}

public enum MCR{
MCR,MCREQ,MCRNE,MCRHS,MCRLO,MCRMI,
MCRPL,MCRVS,MCRVC,MCRHI,MCRLS,MCRGE,MCRLT,MCRGT,
MCRLE,MCRAL,MCR2
}


public enum MRC{
MRC,MRCEQ,MRCNE,MRCHS,MRCLO,MRCMI,
MRCPL,MRCVS,MRCVC,MRCHI,MRCLS,MRCGE,MRCLT,MRCGT,
MRCLE,MRCAL,MRC2
}


public enum SMLAL{
SMLAL,SMLALEQ,SMLALNE,SMLALHS,SMLALLO,SMLALMI,
SMLALPL,SMLALVS,SMLALVC,SMLALHI,SMLALLS,SMLALGE,SMLALLT,SMLALGT,
SMLALLE,SMLALAL,
SMLALS,SMLALEQS,SMLALNES,SMLALHSS,SMLALLOS,SMLALMIS,
SMLALPLS,SMLALVSS,SMLALVCS,SMLALHIS,SMLALLSS,SMLALGES,SMLALLTS,SMLALGTS,
SMLALLES,SMLALALS
}


public enum STR{
STR
}

public enum STRB{
STRB
}

public enum STRH{
STRH
}

public enum SWI{
SWI,SWIEQ,SWINE,SWIHS,SWILO,SWIMI,
SWIPL,SWIVS,SWIVC,SWIHI,SWILS,SWIGE,SWILT,SWIGT,
SWILE,SWIAL
}


public enum UMLAL{
UMLAL,UMLALALS
}

public enum UMULL{
UMULL,UMULLALS
}



public enum shift{
ROR,LSL,LSR,RRX,ASR
}

}
