/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StepRunWindow.java
 *
 * Created on Mar 18, 2012, 12:56:45 PM
 */
package frontend;

import backend.Memory;
import backend.StepRun;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author Dr Rakesh Malhotra
 */
public class StepRunWindow extends javax.swing.JFrame {
static StepRun obj;
static File path;

public static Highlighter.HighlightPainter cyanPainter;
    /** Creates new form StepRunWindow */
    public StepRunWindow(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        cyanPainter = new DefaultHighlighter.DefaultHighlightPainter(
				Color.cyan);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        programdisplay = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        steprun = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setTitle("Step Run");

        programdisplay.setEditable(false);
        jScrollPane1.setViewportView(programdisplay);
        //programdisplay.setEditorKit(new NumberedEditorKit());
        try{
            programdisplay.read(new FileReader(path), null);
        }
        catch(Exception e)
        {

        }
        programdisplay.setHighlighter(new frontend.MyHighlighter());
        programdisplay.setSelectionColor(new Color(1.0f, 1.0f, 1.0f, 0.0f));

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        steprun.setText("Step Run");
        steprun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steprunActionPerformed(evt);
            }
        });

        jButton2.setText("Run");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setEditable(false);
        jTextField1.setText("0");

        jLabel1.setText("Line Number");

        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setText("**End of File Reached");
        warning.setVisible(false);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(steprun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warning)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(warning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(steprun)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void steprunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steprunActionPerformed
   
    FrontEnd.exceptionraised=0;
    handlers.clean_branchtable();
        handlers.clean_memtable();
     FrontEnd.activepane.getHighlighter().removeAllHighlights();   
    Integer ct=new Integer(0);
     
    ct=backend.FirstPass.scan(path);
//    obj = new StepRun(path);
    
    
    obj.t.start();
    handlers.update_branchtable(ct);
    (new handlers()).update(0);
    int memref_ct = Memory.display();
    if (memref_ct > 0) {
        handlers.update_memorytable(memref_ct);
                
            }
           if(FrontEnd.exceptionraised!=0)
               FrontEnd.statuswindow.append("ERROR IN EXECUTION \n");frontend.FrontEnd.statuswindow.setCaretPosition(frontend.FrontEnd.statuswindow.getText().length());// TODO add your handling code here:
}//GEN-LAST:event_steprunActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
FrontEnd.exceptionraised=0;
    handlers.clean_branchtable();
        handlers.clean_memtable();
     programdisplay.getHighlighter().removeAllHighlights();   
    Integer ct=new Integer(0);
    ct=backend.FirstPass.scan(path);
    FrontEnd.statuswindow.append("run :\n");frontend.FrontEnd.statuswindow.setCaretPosition(frontend.FrontEnd.statuswindow.getText().length());
    backend.ScanFile ob=new backend.ScanFile(path);
              
  //  jTextField1.setText(String.valueOf(backend.ScanFile.curent_line));
    handlers.update_branchtable(ct);
    (new handlers()).update(0);
    int memref_ct = Memory.display();
    if (memref_ct > 0) {
        handlers.update_memorytable(memref_ct);
                
            }
           if(FrontEnd.exceptionraised!=0)
               FrontEnd.statuswindow.append("ERROR IN EXECUTION \n");frontend.FrontEnd.statuswindow.setCaretPosition(frontend.FrontEnd.statuswindow.getText().length());// TODO add your handling code here:
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void call(File filepath) {
        path=filepath;
      
    try {
             backend.Register.r[15].b=0;
             File f = path;
             backend.ScanFile.br=new RandomAccessFile(f,"rw");
             backend.ScanFile.pos=backend.ScanFile.br.getFilePointer();
             backend.ScanFile.curent_line=new Integer(0);
          //   String name = frontend.FrontEnd.Editor.getToolTipTextAt(frontend.FrontEnd.Editor.getSelectedIndex());
//        name=name.substring(0, name.length()-1).concat("obj");
      
         /*try {
           // backend.ScanFile.outbin = new BufferedWriter(new FileWriter(name));
        } catch (IOException ex) {
            ex.printStackTrace();
        }*/
        } catch (IOException ex) {
           frontend.FrontEnd.statuswindow.append("ERROR in line "+backend.ScanFile.curent_line+1+": Unable to access the source file:"+path.getName()+" \n");
           frontend.FrontEnd.statuswindow.setCaretPosition(frontend.FrontEnd.statuswindow.getText().length());frontend.FrontEnd.exceptionraised++;  
           return;
        } 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StepRunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StepRunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StepRunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StepRunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                StepRunWindow dialog = new StepRunWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JEditorPane programdisplay;
    public static javax.swing.JButton steprun;
    public static javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
